import { LegalRole } from "../types/user.types"

export const LEGAL_PERMISSIONS = {
  // Document
  DOCUMENT_VIEW: "legal.document.view",
  DOCUMENT_UPLOAD: "legal.document.upload",
  DOCUMENT_EDIT: "legal.document.edit",
  DOCUMENT_DELETE: "legal.document.delete",
  DOCUMENT_SUBMIT: "legal.document.submit",
  DOCUMENT_RESUBMIT: "legal.document.resubmit",

  // Review
  REVIEW_PERFORM: "legal.review.perform",
  REVIEW_COMMENT: "legal.review.comment",
  REVIEW_REQUEST_REVISION: "legal.review.request_revision",
  REVIEW_PASS: "legal.review.pass",

  // Approval
  APPROVAL_APPROVE: "legal.approval.approve",
  APPROVAL_REJECT: "legal.approval.reject",

  // Request & Task
  REQUEST_CREATE: "legal.request.create",
  REQUEST_MANAGE: "legal.request.manage",
  TASK_ASSIGN: "legal.task.assign",
  TASK_UPDATE: "legal.task.update",

  // Audit
  AUDIT_VIEW: "legal.audit.view",
} as const

export type LegalPermission = (typeof LEGAL_PERMISSIONS)[keyof typeof LEGAL_PERMISSIONS]

export const ROLE_PERMISSIONS: Record<LegalRole, LegalPermission[]> = {
  LEGAL_PIC: [
    LEGAL_PERMISSIONS.DOCUMENT_VIEW,
    LEGAL_PERMISSIONS.DOCUMENT_UPLOAD,
    LEGAL_PERMISSIONS.DOCUMENT_SUBMIT,
    LEGAL_PERMISSIONS.DOCUMENT_RESUBMIT,
    LEGAL_PERMISSIONS.REVIEW_PERFORM,
    LEGAL_PERMISSIONS.REVIEW_COMMENT,
    LEGAL_PERMISSIONS.REVIEW_REQUEST_REVISION,
    LEGAL_PERMISSIONS.REVIEW_PASS,
    LEGAL_PERMISSIONS.REQUEST_CREATE,
    LEGAL_PERMISSIONS.REQUEST_MANAGE,
    LEGAL_PERMISSIONS.TASK_ASSIGN,
    LEGAL_PERMISSIONS.TASK_UPDATE,
    LEGAL_PERMISSIONS.AUDIT_VIEW,
  ],
  LEGAL_STAFF: [
    LEGAL_PERMISSIONS.DOCUMENT_VIEW,
    LEGAL_PERMISSIONS.DOCUMENT_UPLOAD,
    LEGAL_PERMISSIONS.REVIEW_COMMENT,
    LEGAL_PERMISSIONS.REQUEST_CREATE,
    LEGAL_PERMISSIONS.TASK_UPDATE,
    LEGAL_PERMISSIONS.AUDIT_VIEW,
  ],
  BUSINESS_DEV_PIC: [
    LEGAL_PERMISSIONS.DOCUMENT_VIEW,
    LEGAL_PERMISSIONS.DOCUMENT_UPLOAD,
    LEGAL_PERMISSIONS.DOCUMENT_SUBMIT,
    LEGAL_PERMISSIONS.DOCUMENT_RESUBMIT,
    LEGAL_PERMISSIONS.REVIEW_COMMENT,
    LEGAL_PERMISSIONS.REQUEST_CREATE,
    LEGAL_PERMISSIONS.AUDIT_VIEW,
  ],
  FINANCE_PIC: [
    LEGAL_PERMISSIONS.DOCUMENT_VIEW,
    LEGAL_PERMISSIONS.DOCUMENT_UPLOAD,
    LEGAL_PERMISSIONS.DOCUMENT_SUBMIT,
    LEGAL_PERMISSIONS.REVIEW_COMMENT,
    LEGAL_PERMISSIONS.REQUEST_CREATE,
    LEGAL_PERMISSIONS.AUDIT_VIEW,
  ],
  PROJECT_PIC: [
    LEGAL_PERMISSIONS.DOCUMENT_VIEW,
    LEGAL_PERMISSIONS.DOCUMENT_UPLOAD,
    LEGAL_PERMISSIONS.DOCUMENT_SUBMIT,
    LEGAL_PERMISSIONS.REVIEW_COMMENT,
    LEGAL_PERMISSIONS.REQUEST_CREATE,
    LEGAL_PERMISSIONS.AUDIT_VIEW,
  ],
  DIRECTOR: [
    LEGAL_PERMISSIONS.DOCUMENT_VIEW,
    LEGAL_PERMISSIONS.REVIEW_COMMENT,
    LEGAL_PERMISSIONS.APPROVAL_APPROVE,
    LEGAL_PERMISSIONS.APPROVAL_REJECT,
    LEGAL_PERMISSIONS.REQUEST_CREATE,
    LEGAL_PERMISSIONS.AUDIT_VIEW,
  ],
  ADMIN: Object.values(LEGAL_PERMISSIONS),
}
